ems/ems/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls' , namespace='home')),
]

ems/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('home/',views.index,name='index'),
    path('add_emp/',views.add_emp,name='add_emp'),
    path('remove_emp/',views.remove_emp,name='remove_emp'),
    path('remove_emp/<int:emp_id>',views.remove_emp),
    path('all_emp/',views.all_emp,name='all_emp'),
    path('filter_emp/',views.filter_emp,name='filter_emp')
    
]

ems/home/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=255,null=False)
    location = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}"

class Role(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Employee(models.Model):
    first_name = models.CharField(max_length=100,null=False)
    last_name = models.CharField(max_length=100)
    dept = models.ForeignKey(Department,on_delete=models.CASCADE)
    salary = models.IntegerField(default=0)
    bonus = models.IntegerField(default=0)
    role = models.ForeignKey(Role,on_delete=models.CASCADE)
    phone = models.IntegerField(default=0)
    hire_date = models.DateField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

ems/home/views.py
from datetime import date
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Employee,Role,Department
from .form import EmployeeForm
from django.db.models import Q

# Create your views here.

def index(request):
    return render(request,'index.html')

def add_emp(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
          employee = form.save(commit = False)  
          employee.hire_date = date.today()
          employee.save()
          return redirect('home:all_emp')
    else:
        form = EmployeeForm()
    return render(request,'add_emp.html',{'form':form})

def remove_emp(request,emp_id=0):
    if emp_id:
        try:
            removed_emp = Employee.objects.get(id=emp_id)
            removed_emp.delete()
            return redirect('home:all_emp')
        except:
            return HttpResponse("Some Error Occured")
    emps = Employee.objects.all()
    context = {
        'emps':emps
    }
    return render(request,'remove_emp.html',context)

def all_emp(request):
    emps = Employee.objects.all()
    context = {
        'emps':emps
    }
    return render(request,'all_emp.html',context)

def filter_emp(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        dept = request.POST.get('dept')
        role = request.POST.get('role')
        emps = Employee.objects.all()
        if name:
            emps = emps.filter(Q(first_name__icontains=name)| Q(last_name__icontains=name))
        if dept:
            emps = emps.filter(dept__name__icontains=dept)
        if role:
            emps = emps.filter(role__name__icontains =role)
        context = {
            'emps':emps,
            'name': name,  
            'dept': dept,
            'role': role,
        }
        return render(request,'all_emp.html',context)
    
    else:
        return render(request,'filter_emp.html')

ems/home/templates/add_emp.html
{% extends "base.html" %}
{%load static%}
<h1>
{%block heading%}

Add Employee

{%endblock heading%}
</h1>
{%block content%}
    <div class = 'container mt-3 border border-dark p-3' style = "text-align:center;">
        <form method = 'POST'>
            <h3 style = "text-align:center;"> Employee Form </h3>
             {% csrf_token %}
             {{form.as_p}}
             <button type = 'submit'> Submit </button>
        </form>
    </div>
{%endblock content%}

ems/home/templates/all_emp.html
{% extends "base.html" %}
{%load static%}
<h1>
{%block heading%}

All Employees

{%endblock heading%}
</h1>
{%block content%}
    <div class = "container">
    <table class="table table-success table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Department</th>
      <th scope="col">Salary</th>
      <th scope="col">Bonus</th>
      <th scope="col">Role</th>
      <th scope="col">Phone number</th>
      <th scope="col">Hire Date</th>
    </tr>
  </thead>
  {%for emp in emps %}
  <tbody>
    <tr>
      <td>{{emp.id}}</td>
      <td>{{emp.first_name}}</td>
      <td>{{emp.last_name}}</td>
      <td>{{emp.dept}}</td>
      <td>{{emp.salary}}</td>
      <td>{{emp.bonus}}</td>
      <td>{{emp.role}}</td>
      <td>{{emp.phone}}</td>
      <td>{{emp.hire_date}}</td>
    </tr>
  </tbody>
  {% endfor %}
</table>
{%endblock content%}

ems/home/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Office Employment Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>
  <body>
    <div class="container mt-3">
        <h1>{% block heading%} {%endblock heading%}</h1>
        <hr>
        <a class="btn btn-primary" href="{%url 'home:all_emp' %}" role="button">View all Employee</a>
        <a class="btn btn-primary" href="{%url 'home:add_emp' %}" role="button">Add Employee</a>
        <a class="btn btn-primary" href="{%url 'home:remove_emp' %}" role="button">Remove Employee</a>
        <a class="btn btn-primary" href="{%url 'home:filter_emp' %}" role="button">Filter Employee Details</a>
    </div>
    {%block content%}
    {%endblock content%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>  
</body>
</html>

ems/home/templates/filter_emp.html
{% extends "base.html" %}
{%load static%}
<h1>
{%block heading%}

All Employees

{%endblock heading%}
</h1>
{%block content%}
    <div class = "container">
        <form method='POST'>
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" name='name' class="form-control" value = '{{name}}'>
        </div>
        <div class="mb-3">
            <label for="dept" class="form-label">Department</label>
            <input type="text" name= 'dept' class="form-control" value = '{{value}}'>
        </div>
         <div class="mb-3">
            <label for="role" class="form-label">Role</label>
            <input type="text" name = 'role' class="form-control" value = '{{role}}'>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{%endblock content%}

ems/home/templates/index.html
{% extends "base.html" %}
{%load static%}
<h1>
{%block heading%}

Employee Management System

{%endblock heading%}
</h1>
{%block content%}

{%endblock content%}

ems/home/templates/remove_emp.html
{% extends "base.html" %}
{%load static%}
<h1>
{%block heading%}

All Employees

{%endblock heading%}
</h1>
{%block content%}
    <div class = "container">
    <table class="table table-success table-striped mt-3">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Department</th>
      <th scope="col">Salary</th>
      <th scope="col">Bonus</th>
      <th scope="col">Role</th>
      <th scope="col">Phone number</th>
      <th scope="col">Hire Date</th>
      <th scope="col"> Action </th>
    </tr>
  </thead>
  {%for emp in emps %}
  <tbody>
    <tr>
      <td>{{emp.id}}</td>
      <td>{{emp.first_name}}</td>
      <td>{{emp.last_name}}</td>
      <td>{{emp.dept}}</td>
      <td>{{emp.salary}}</td>
      <td>{{emp.bonus}}</td>
      <td>{{emp.role}}</td>
      <td>{{emp.phone}}</td>
      <td>{{emp.hire_date}}</td>
      <td> <a class="btn btn-danger" href='/remove_emp/{{emp.id}}' role='button'>Delete</button>
    </tr>
  </tbody>
  {% endfor %}
</table>
{%endblock content%}